In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
np.unique(train_labels)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [11]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [12]:
train_images = train_images / 255.0

test_images = test_images / 255.0


In [14]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [16]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 1.0895 - accuracy: 0.6585
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.6413 - accuracy: 0.7700
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5673 - accuracy: 0.7952
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.5254 - accuracy: 0.8129
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4973 - accuracy: 0.8236


In [17]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 894us/step - loss: 0.5094 - accuracy: 0.8155
Test accuracy: 0.815500020980835


In [18]:
predictions = model.predict(test_images)

In [19]:
predictions[0]

array([2.9808009e-06, 2.0970461e-07, 2.2354920e-05, 2.2812925e-05,
       2.4895227e-05, 1.4318819e-01, 3.0000638e-05, 3.9487165e-01,
       7.2997529e-03, 4.5453718e-01], dtype=float32)

In [20]:
np.argmax(predictions[0])

9

In [21]:
test_labels[0]

9

In [22]:
img = test_images[0]

print(img.shape)

(28, 28)


In [23]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [24]:
predictions_single = model.predict(img)

print(predictions_single)

[[2.9808039e-06 2.0970442e-07 2.2354963e-05 2.2812927e-05 2.4895229e-05
  1.4318837e-01 3.0000640e-05 3.9487129e-01 7.2997566e-03 4.5453721e-01]]


In [26]:
np.argmax(predictions_single[0])

9